<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault><ApplicationIcon>Assets/ReimaginedModStudio.ico</ApplicationIcon></PropertyGroup>
  <ItemGroup><AvaloniaResource Include="Assets/ReimaginedModStudio.ico" /><AvaloniaResource Include="Assets/ReimaginedModStudio.png" /></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ModStudio.Core/ModStudio.Core.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.2" />
    <PackageReference Include="Markdown.Avalonia.Tight" Version="12.0.0-a1" />
    <PackageReference Include="Markdig" Version="1.3.2" />
  </ItemGroup>
</Project>
